name: 'Create Unity Project'
description: 'Create empty Unity3D project'
author: 'nowsprinting'

inputs:
  project-path:
    required: false
    description: 'Path of the Unity project to be created, relative from repository root (/github/workspace).'
    default: 'UnityProject~'

outputs:
  created-project-path:
    description: 'Path of the created Unity project, relative from repository root (/github/workspace).'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'gray-dark'