name: 'build-test'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types: [ opened, synchronize, reopened ]  # Same as default
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          npm ci
          npm run all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test this action
        uses: ./
        with:
          project_path: UnityProject~
        id: test

      - name: Verify output
        run: test "${{ steps.test.outputs.created_project_path }}" = "UnityProject~"

      - name: Verify export environment variable
        run: test "${{ env.created_project_path }}" = "UnityProject~"

      - name: Verify created project
        run: |
          ls -la "${{ steps.test.outputs.created_project_path }}"

  notify:
    needs: [ build, test ]
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - uses: Gamesight/slack-workflow-status@v1.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
